# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Health Card CI

on:
  push:
    branches: [ master ]
    paths:
      - "**" 
      - '!**.md'
  pull_request:
    paths:
      - "**" 
      - '!**.md'
  release:
    types:
      - created
  

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2.3.4
    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Cache Gradle wrapper
      id: cache-gradle-wrapper
      uses: actions/cache@v2.1.4
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-dependencies-
    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v2.1.4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-dependencies-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-dependencies-
    - name: Check And Test
      run: ./gradlew check
      
  build:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2.3.4
    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Cache Gradle wrapper
      id: cache-gradle-wrapper
      uses: actions/cache@v2.1.4
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-dependencies- 
    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v2.1.4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-dependencies-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-dependencies-
    - name: Build with Gradle
      run: ./gradlew clean build -x test
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: health-card-job-jar
        path: build/libs
        retention-days: 1

  docker-release:
    needs: [build]
    name: Build Docker container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2.3.4
    - name: Download health card job jar
      uses: actions/download-artifact@v2.0.8
      with:
        name: health-card-job-jar
        path: build/libs
    - name: Cache Gradle wrapper
      id: cache-gradle-wrapper
      uses: actions/cache@v2.1.4
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-dependencies-
    - name: Get version of health_card_job
      id: get_health_card_job_version
      run: |
          version=$(./gradlew -q projectVersion)
          echo "Trying to build and publish health_card_job:${version}"
          echo "HEALTH_CARD_VERSION=${version}" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.0.1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.1.1
    - name: Docker Login Tencent Registry
      uses: docker/login-action@v1.8.0
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64
        tags: |
          ${{ secrets.DOCKER_REGISTRY }}:latest
          ${{ secrets.DOCKER_REGISTRY }}:${{ env.HEALTH_CARD_VERSION }}
      
  docker-deploy:
    needs: [docker-release]
    name: Pull Docker container and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Pull and deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            if test ! -z "$(docker ps --filter ancestor=uswccr.ccs.tencentyun.com/chokho_workspace/health_card -q)"; 
            then 
            docker stop $(docker ps --filter ancestor=${{ secrets.DOCKER_REGISTRY }} -q)
            docker rm -f $(docker ps -a --filter ancestor=${{ secrets.DOCKER_REGISTRY }}:latest -q)
            docker rmi -f $(docker images  ${{ secrets.DOCKER_REGISTRY }}:latest -q);
            fi;
            docker login --username=${{ secrets.REGISTRY_USERNAME }} --password=${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}
            docker pull ${{ secrets.DOCKER_REGISTRY }}:latest
            docker run -d -p ${{ secrets.HOST_PORT }}:${{ secrets.CONTAINER_PORT }} ${{ secrets.DOCKER_REGISTRY }}:latest --restart=always --name=health-card
